### ISSUE TITLE
Bellows not showing up in Manage Modules

### ISSUE THREAD

**Issue by Motara7** [casualchameleon/Bellows#10]
I have extracted Bellows to /Data/modules/Bellows-master and I have restarted Foundry and my PC several times. Bellows does not appear in Manage Modules. I'm using Foundry VTT 0.7.7 and (if it matters) Pathfinder 1 0.76.4.

Is there a dependency or or something that might prevent it from showing up?

**Comment by casualchameleon** [comment]
Hey, not sure why you've unzipped the source directly into your modules directory. The correct way to install is to import the module using the manifest found [here](https://raw.githubusercontent.com/casualchameleon/Bellows/master/module.json). If you're not sure how to do it, I suggest googling a tutorial.

I'm not aware of any incompatibilities with FVTT 0.7.7 or the PF1 system. If you still have trouble finding the module after installing it through the manifest, let me know and I'll investigate. I'm extremely busy at the moment with a house move so haven't had much time for Bellows!

**Comment by casualchameleon** [comment]
Hi, @Motara7 did you manage to get this working?

**Comment by Motara7** [comment]
Yes. I did. Sorry for not responding.
