### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by SamF111** [casualchameleon/Bellows#11]
Hi,
Module works great, but it's throwing a lot of errors in the chrome log (Ctrl shift J).
Are you aware of this?

![image](https://user-images.githubusercontent.com/5872655/101983118-aceaba00-3c70-11eb-9fac-3ec09e698d85.png)

**Comment by casualchameleon** [comment]
Weird. This looks like it could be the youtube iframe api itself erroring. Does this happen on playlist import or during playback (or both)?

**Comment by casualchameleon** [comment]
Closing this as I cannot replicate and have released a new version of Bellows.
