### ISSUE TITLE
Playlist Import confusing track titles

### ISSUE THREAD

**Issue by jamie** [casualchameleon/Bellows#15]
I'm just clicking around a bit, and found that when trying to import https://www.youtube.com/playlist?list=OLAK5uy_mi0e9r4bmBnfVRUPzmBXVtsKxDOu8JvAg it's giving me some borked track titles:

<img width="522" alt="Start • Foundry Virtual Tabletop 2021-02-03 15-52-06" src="https://user-images.githubusercontent.com/1093/106824491-c6d4c780-6637-11eb-90c3-e5266f0f334e.png">

Actually going through the import, it does look like it's doubling up on the imported tracks, rather than just being a display issue.

**Comment by casualchameleon** [comment]
Having trouble replicating this. Have tried this playlist and several others this morning. That definitely shouldn't be happening. Could you let me know what browser you're using?

Thanks for the report!

**Comment by casualchameleon** [comment]
Please can you try the new release and see if this issue persists in 0.4.1 of Bellows. Open a new ticket if it does, thanks.
