### ISSUE TITLE
Music not playing unless I adjust sound volume

### ISSUE THREAD

**Issue by NRschwier** [casualchameleon/Bellows#18]
Hello!

I really love your module and it has really helped me, but lately I am having a weird issue.  Whenever I play a list in foundry, nothing will play until I change the individual playing sounds volume. I only need to tweak it a little for it to start playing but this is troublesome with big playlists as I have to click and change the volume every 3 minutes.

**Comment by casualchameleon** [comment]
Hi, sorry for the delay in getting back to you. Do you have any errors in your console? What browser are you using? do your sounds play for players without you having to adjust the sound? Thanks.

**Comment by casualchameleon** [comment]
Please can you try the latest version of bellows and let me know if the issue persists
