### ISSUE TITLE
Download points to old version

### ISSUE THREAD

**Issue by MrBrentRogers** [casualchameleon/Bellows#2]
points at "download": "https://github.com/temportalflux/MusicAssist/releases/download/v0.1.0/MusicAssist-v0.1.0.zip",
from https://github.com/casualchameleon/MusicAssist/blob/v0.2.1/module.json
download should be pointing to https://github.com/casualchameleon/MusicAssist/ yada

**Comment by casualchameleon** [comment]
Hi I have not done this yet as this fork is not an official release of MA, however, I've spoken to temportalflux and will be rebranding this fork and releasing it as its own thing... stay tuned

**Comment by casualchameleon** [comment]
You can now point foundry to my fork of MusicAssist here: https://raw.githubusercontent.com/casualchameleon/Bellows/master/module.json

I recommend you remove MusicAssist first.
