### ISSUE TITLE
Update track button not working under 8.5

### ISSUE THREAD

**Issue by themockster** [casualchameleon/Bellows#20]
Hello! 

Well I know Bellows isn't officially supported on Beta 8.5 yet, but I wanted to flag that I'm unable to click "Update Track" with Bellows installed when choosing a youtube streamed ID. 

It simply does not do anything when I click on it.

**Comment by Fish9494** [comment]
In the web console, it throws an error from PlayListSoundConfig.cs on line 31:

this.playlist.updateEmbeddedEntity("PlaylistSound", formData, {});

I'm not the developer just thought this note would be helpful

**Comment by StyrmirThorarins** [comment]
Same under Foundry VTT 8.6.

"TypeError: Cannot read property 'createEmbeddedEntity' of undefined
    at PlaylistSoundConfig.<anonymous> (http://localhost:1802/modules/bellows/modules/patches/PlaylistSoundConfig.js:33:21)
    at PlaylistSoundConfig.proto.<computed> (http://localhost:1802/modules/bellows/modules/patches/patcher.js:8:12)
    at PlaylistSoundConfig._onSubmit (http://localhost:1802/scripts/foundry.js:2816:18)"

![url audio stream](https://user-images.githubusercontent.com/12521824/121782173-c9bc6780-cb97-11eb-96d0-8596162b8ff2.jpg)
![url audio stream 2](https://user-images.githubusercontent.com/12521824/121782176-cc1ec180-cb97-11eb-911b-3d1a4cfa2f5b.jpg)
![url audio stream 3](https://user-images.githubusercontent.com/12521824/121782177-ce811b80-cb97-11eb-9775-39989d73755f.jpg)

**Comment by casualchameleon** [comment]
Looks like some big API changes have broken Bellows' core functionality. I'll put a fix out tomorrow. I think there's a PR that gets this all working again so I'll take a look at that first. Thanks for the info/reports.

**Comment by Cussa** [comment]
Hello. I tried to install the latest version which has the PR #22 , however it seems that we are still having issues to update the tracks

**Comment by casualchameleon** [comment]
Hey Cussa. The latest version does not include PR #22 unless you are building from source. However, even with that PR the module is nigh unusable. 0.8 has changed vast portions of the API so a huge chunk of bellows is not working. This might take more than a day or two. I have some fixes in the pipeline already but I don't think there'll be a new version released today.

**Comment by casualchameleon** [comment]
This has now been fixed, thanks.
