### ISSUE TITLE
Ambient Songs not working

### ISSUE THREAD

**Issue by CyberneticDots** [casualchameleon/Bellows#21]
Im not sure if this is due to the 7.10 update Foundry just got, but songs i streamed into my playlists will not transfer over into Ambient Sounds when dragged.

![image](https://user-images.githubusercontent.com/85000086/120053052-c2208e80-bfed-11eb-9719-cb054d314aa5.png)

Gives me this when i do so.

The module is A+ tho, the streaming makes it WAY easier than downloading. Thank you!

**Comment by casualchameleon** [comment]
Thanks, looks like it could be to do with an update to foundry. I'm going to be fixing it to support the latest version so I'll make sure this works in my testing.

**Comment by CyberneticDots** [comment]
Thank you kindly and thank you for all your hard work!

**Comment by casualchameleon** [comment]
Fixed (get latest)
