### ISSUE TITLE
Tracks not playing on 8.6

### ISSUE THREAD

**Issue by raulrozza** [casualchameleon/Bellows#23]
Can't play tracks with the new 8.6 version.

The songs can be played by clicking the *Play Playlist* button, but not on the *Play Sound*.

Console is giving **TypeError: sound.flags is undefined**

### Call stack:
![image](https://user-images.githubusercontent.com/38353761/121105316-463af900-c7da-11eb-9a30-285da7ff4986.png)

**Comment by casualchameleon** [comment]
Hi, This is being looked at. Thanks very much for the report

**Comment by uniwars** [comment]
Hi, if it can help I get that in the console when trying to play sound in 0.8.7 : https://prnt.sc/168f9hz

**Comment by casualchameleon** [comment]
Hi, thanks for the screenshot. I'm working on a huge overhaul to the module to get it working in 8.x. I expect to have it done this week some time, at least in a limited fashion.

**Comment by uniwars** [comment]
hi, any update ?

**Comment by casualchameleon** [comment]
Hi, work got in the way so the update's been a little delayed. I'm almost done writing the implementation code, then I'll start testing before releasing an unstable beta

**Comment by casualchameleon** [comment]
Small update - playlist playback is now working. I'm currently porting the playlist import over which shouldn't take long at all, then I'll create a prelease version for feedback

**Comment by casualchameleon** [comment]
Should be fixed now.
