### ISSUE TITLE
Wrong Manifest URL

### ISSUE THREAD

**Issue by jbblily** [casualchameleon/Bellows#29]
It makes an error mesage that foundry can't find https://raw.githubusercontent.com/casualchameleon/Bellows/releases/latest/download/module.json

Please check out the manifest url. Thank you for your hard work.

**Comment by casualchameleon** [comment]
Thanks, this has already been fixed - it was an issue with the deployment. Please reinstall bellows using the manifest URL in the readme or the following link: https://github.com/casualchameleon/Bellows/releases/latest/download/module.json

Sorry for the inconvenience - it won't affect any tracks or playlists you've already set up.
