### ISSUE TITLE
Using Stream Utils together with Forked Music Assist messes up /stream

### ISSUE THREAD

**Issue by SimonLain** [casualchameleon/Bellows#3]
I use the /stream version of the website for my stream overlay and when turning on a song it squeeze's everything to the side (picture attached). Is there a way to fix this so that Music Assist doesn't pop up in /stream or have it's own fixed space so it doesn't bump other modules/core chat?

Link to Stream Utils module used: https://foundryvtt.com/packages/0streamutils/ Creator: ardittristan#0001

botch fix: The Stream Utils mod offers a way to disable modules in /stream but this might not be a good thing and is definitely a botch.
![ApplicationFrameHost_GHr9olJVFE](https://user-images.githubusercontent.com/32328214/96913009-61ebcc00-14a3-11eb-9bb9-9393597a232b.png)

**Comment by casualchameleon** [comment]
This has been fixed. I've also rebranded this fork as 'Bellows' so if you want to use this, please remove musicassist and add the module using this link: https://raw.githubusercontent.com/casualchameleon/Bellows/master/module.json
Cheers.
