### ISSUE TITLE
[Question] Format of youtube playlists

### ISSUE THREAD

**Issue by KJTailor** [casualchameleon/Bellows#31]
I love the idea of being able to import YouTube playlists into my Foundry games, but so far it is not working for me.
I have the most recent version of Bellows installed and my Foundry is on 0.8.8.

When I try to import a playlist made by myself, I get an error message saying "www.youtube.com is different from expected value [local host IP]"
This happens for playlist that I try to import with the format [https://www.youtube.com/playlist?list=ifguyeg]. Mind you I have only tried playlists I made myself, for this purpose.

If I try to import single videos of the format [https://youtu.be/dAS3Wh-h6R0] or [https://www.youtube.com/watch?v=dAS3Wh-h6R0&ab] it starts importing.

On this note, how long is the expected import time for a single video or a whole playlist?

Thanks for the help.

**Comment by casualchameleon** [comment]
Hi mate, thanks for getting in touch.
https://www.youtube.com/playlist?list=ifguyeg is not a valid playlist. The format looks fine, but if I follow that link it goes to the youtube homepage. It may be that you've set it to private? Private playlists and videos will not work.

Just to make sure too, you're importing using the import tool at the bottom of the sounds tab in Foundry? I got a different error to the one you mentioned when I tried to import the playlist.

**Comment by KJTailor** [comment]
Oh my god, I didn't even think about the privacy setting potentially affecting Bellows! It absolutely makes sense though.

Thanks for getting back to me so quickly.

As for the YouTube playlists, I was more concerned about the format of them, so I just scrambles some letters into it. As I said, I didn't even think of the privacy settings. The correct playlist would be [https://www.youtube.com/playlist?list=PLqcf768HRYVj9-mHYgLVuKdU_gI8KSxnP](url).

> Just to make sure too, you're importing using the import tool at the bottom of the sounds tab in Foundry? I got a different error to the one you mentioned when I tried to import the playlist.

Yes, I am using that import tool. How long should a normal playlist import take?

**Comment by casualchameleon** [comment]
The import service understands IDs and full URLs. In your case you could either drop in https://www.youtube.com/playlist?list=PLqcf768HRYVj9-mHYgLVuKdU_gI8KSxnP or PLqcf768HRYVj9-mHYgLVuKdU_gI8KSxnP and the import would complete.

A playlist of a hundred tracks takes me 2 or 3 seconds although I haven't benchmarked it. It's relatively quick. This can change depending on your internet connection though

**Comment by KJTailor** [comment]
Alright, everything is working fine now. Imports happen fast and exactly as they should. Thank you again for your help :)

**Comment by casualchameleon** [comment]
Any time, thanks for getting in touch!
