### ISSUE TITLE
Bellows suddenly streaming video to foundry in addition to audio.

### ISSUE THREAD

**Issue by cojinx303** [casualchameleon/Bellows#33]
Today bellows is opening a youtube video in the upper left corner of the Foundry window that plays the video in addition to the sound. It can't be minimized or closed. This is super undesireable. I can't find a setting to stream just the audio. I have never seen this before, and an issue posted a couple days makes me believe this is not intended behavior.

**Comment by cojinx303** [comment]
I have some more info. While bellows was playing a playlist (and after I shut it down)I was unable to open any maps. I restarted Foundry and was able to load maps as per normal, and playing Bellows no longer played the Youtube video.

**Comment by casualchameleon** [comment]
Hi, thanks for the report.

Bellows uses the youtube Iframe API and always has the player in the top left, but as you said it's only visible when there's no active scene. There's not really a way around this. I have tried hiding it with CSS but it seems to override it. I can take another look at it.

I'll investigate not being able to create scenes while Bellows is playing video too, though in my testing this worked fine.

**Comment by johcker** [comment]
One of my players is having the same problem. His PC may be a little older than those of other players, can that give you any hints of what's going on? Image attached.

![20210814_210729 (1)](https://user-images.githubusercontent.com/2867140/129464028-83447883-624f-48d2-bbaa-9554282aee43.jpg)

**Comment by KJTailor** [comment]
Just to latch onto this, one of my players has exactly the same issue. It apparently happened every time the song/video changed?
![235050462_542936013796189_2621753824422332557_n](https://user-images.githubusercontent.com/87787745/129889713-3e052c6f-4d42-499d-8dd1-ca8c7837ae50.jpg)

**Comment by Xyxzor** [comment]
Also seeing this happen.

**Comment by mathsteck** [comment]
Hello, I'm facing a similar issue. In our case the user also have an old notebook and sometimes his map/scene disappears out of nowhere and the video start streaming in it's place requiring him to restart the tab in order to play. I've noticed that it happens when I start playing any Youtube videos.

**Comment by revilowaldow** [comment]
Also getting this issue. You should be able to hide the box by setting it's height and width to 0 x 0 px
`width="0px" height="0px"`

**Comment by casualchameleon** [comment]
Should be fixed in 0.4.4. Please open a new issue if not.
