### ISSUE TITLE
Getting "err blocked by client" when playing songs

### ISSUE THREAD

**Issue by dnf257** [casualchameleon/Bellows#35]
Hey guys, I'm getting "err blocked by client" when attempting to use imported songs. I'll be able to hear them for a second or two then it will cut out. 

![image](https://user-images.githubusercontent.com/66557355/127377291-ef1e9ead-f810-435d-9f17-cafac5a3c5a7.png)

I don't have any other music modules installed.

**Comment by casualchameleon** [comment]
Hi, this is your adblocker blocking the video and nothing to do with Bellows itself. My suggestion is to turn it off on the Foundry site.

**Comment by dnf257** [comment]
Right... I thought of that and turned it off on both foundry and YouTube to
no avail.

**Comment by casualchameleon** [comment]
Sorry you're having trouble. Have you tried a different browser? Some browsers like Brave have built in blockers. I use Firefox with ublock origin and it doesn't cause me any issues with playback.

**Comment by dnf257** [comment]
I'll try it on a few and get back to you, thanks for the quick response.

**Comment by dnf257** [comment]
Tried to run it on Chrome, Firefox as well as in incognito mode on Chrome.
Same issue so far, went ahead and tried it without other modules active as
well.
Could it be I'm using it on The Forge hosting service?

**Comment by casualchameleon** [comment]
I've run Bellows without issue on Forge in the past. The error is specifically your browser blocking part of the iframe loading. Can you completely disable your adblocker, not just for specific sites (it may be that disabling it for youtube/forge-vtt is still blocking third party domains (double click in this instance) and let me know if it works? I use ublock origin and don't have this problem though.

**Comment by dnf257** [comment]
Removed adblock and still having the issue where it will play for a second
or two then nothing. The error message is gone however. Could it be from
youtube's end?

**Comment by casualchameleon** [comment]
Ah that is interesting. So the content isn't being blocked, it's just pausing or ending prematurely. Can you link me the exact video you're trying to play?

**Comment by dnf257** [comment]
Going by the player itself on foundry, the video continues, as in the
player video time is moving forward.

https://www.youtube.com/playlist?list=PLe2-iKXxu4Ej0vzlBVCq_S2y1a_xdsxz5

I've tried a few on this playlist and some others.

**Comment by casualchameleon** [comment]
If the video time is going forward, then the video is definitely playing - the time in foundry is updated by the youtube player itself. I'm wondering if it's muted or just very low volume due to some global settings. I had some trouble with this in testing too but thought I fixed it.

I tried your playlist and the only one that didn't work was the tavern music, whose video is unavailable.

Could you try starting a new world with Bellows enabled. Don't create any scenes, and try importing this playlist again. When you play a video, you should see a youtube player pop up in the top left (this is usually hidden by scenes, hence me asking you to create a new world). Let me know what actually happens - if the video player is set to extremely quiet or something.

Sorry for the delay in getting back to you.

**Comment by casualchameleon** [comment]
Hi, this is almost definitely related to [39](https://github.com/casualchameleon/Bellows/issues/39), which I'm working on a fix for.

**Comment by dnf257** [comment]
So I did what you suggested and everything worked fine! I went back to my
original world and tried a new playlist and it worked...? I did upgrade my
world to 8.8 a couple days ago so maybe that has something to do with it?
the only issue that came up in console was this [image:
chrome_Y7b5r5tpqz.png]

**Comment by dnf257** [comment]
[https://i.imgur.com/9sVBH5q.png](url)

Image from previous comment, sorry for bad pasting^^

**Comment by dnf257** [comment]
https://i.imgur.com/9sVBH5q.png

image from before^ bad pasting.

**Comment by casualchameleon** [comment]
Ah, cool. Yeah, 0.8.6 seems to not work with Bellows. Glad this is sorted for you. I am aware of that deprecation notice. I thought I'd changed everything to use the new call. I'll have to double check. Thanks :)
