### ISSUE TITLE
Error Importing Playlist

### ISSUE THREAD

**Issue by hscissors** [casualchameleon/Bellows#36]
Just tried to import this playlist and got an error saying it wasn't a valid playlist:
https://www.youtube.com/watch?v=BzUZKw3mjkQ&list=PLN7hfyfbw0jwaI2gMqGyybtjLk0VL0xFE

Console error: 
```

bellows.js:1 Bellows ERR | Error: Invalid Playlist
    at a.scrapeVideoNames (bellows.js:1)
    at a.getPlaylistInfo (bellows.js:1)
    at async s.importPlaylist (bellows.js:1)
    at async s._onImport (bellows.js:1)
LogError @ bellows.js:1
```

**Comment by casualchameleon** [comment]
Weird, this imported perfectly for me. Do you have any other console errors?

This error is only thrown when there's an internal error in the Youtube player - it's not from bellows itself.

**Comment by casualchameleon** [comment]
Closing due to no reply
