### ISSUE TITLE
Error: Foundry music page broken after massive playlist import 

### ISSUE THREAD

**Issue by llucasgusmao** [casualchameleon/Bellows#37]
Hello,

I've imported a massive playlist with more than 200 songs (i didn't read the readme before doing this) and then my foundry stoped working while i was changing between musics, I've refreshed the page and then the music page inside foundry get blanked (image bellow) and the music still plays on the background and I can't stop. 

![image](https://user-images.githubusercontent.com/33360785/127756263-8af559bd-dc24-42f1-9f84-3d7c9d4f8b42.png)

I've tried reinstall the module but the error persists, but only on this world, on others the module and the music page works right.

**Comment by casualchameleon** [comment]
Hi, sorry about the issue you're having. Do you have any errors in your console when you hit F12?
