### ISSUE TITLE
Audio plays for a split-second, then silent

### ISSUE THREAD

**Issue by ZacAtakke** [casualchameleon/Bellows#40]
When I play a track I hear a split-second of audio but then nothing. The track appears to be playing as the timer keeps going.

Here's what I see in the console:

![Code](https://user-images.githubusercontent.com/80489317/128611696-35bc3fd3-d07a-48fc-9923-4e556078db87.png)

(I tried stopping and starting the track a few times)

The first violation happens when I pause the track, the others are when I hit play.

**Comment by casualchameleon** [comment]
Hi, thanks for the bug report. What browser are you using? Have you tried disabling extensions? I can't replicate this on edge, chrome or firefox.

**Comment by ZacAtakke** [comment]
I've tried it in chrome with all my extensions off, and I also tried it on edge with no extensions.

**Comment by RoninXiC** [comment]
I do have exactly the same problem since the changes to foundry 0.8. 
Didnt work on Chrome or Firefox. Disabled everything as well...

**Comment by casualchameleon** [comment]
What version of the module are you running? What does it say in the game setup?

**Comment by RoninXiC** [comment]
0.4.1

**Comment by ZacAtakke** [comment]
I'm running:
Bellows 0.4.1
Foundry 0.8.6
5e 1.4.1

**Comment by RoninXiC** [comment]
I just updated foundry to 0.8.8 and it works now

**Comment by casualchameleon** [comment]
Ah ok, maybe I need to test again on 0.8.6 then. I thought it was working, but I have definitely been using 0.8.8 to test. Thanks.

**Comment by ZacAtakke** [comment]
Ohp, that's entirely my bad. Don't know how I missed that, I thought I was on the latest stable version.

Updated to 0.8.8, works for me now. Thanks for this great module!

**Comment by casualchameleon** [comment]
Thanks for helping me get to the bottom of the bug! Very sorry for the inconvenience. I'll make sure to update the readme.
