### ISSUE TITLE
(please help) Bellows does not show up in world

### ISSUE THREAD

**Issue by DuckDungeon** [casualchameleon/Bellows#42]
I see it in my modules when booting up, and I see it to activate it, but it never shows up in configure modules. 

I am extremely novice when trying to install modules straight from github. So I may have done something wrong, but I am at a point where tutorials have done me no good and I just don't know what I don't know. Just asking for help.

This is what the module folder looks like right now. What am I doing wrong?
<img width="206" alt="Screen Shot 2021-08-21 at 12 37 19 AM" src="https://user-images.githubusercontent.com/66494204/130311834-c19ba690-a335-4dad-957a-f9b1709a967c.png">

**Comment by DuckDungeon** [comment]
Opened the module.js file and found a download link to a zip. I entered that into the module folder (see below). Still no luck.

<img width="202" alt="Screen Shot 2021-08-21 at 12 52 19 AM" src="https://user-images.githubusercontent.com/66494204/130312103-5eea4b53-4d73-45b6-89b2-868308e4ac26.png">

**Comment by casualchameleon** [comment]
Hi mate,

No problem. It looks like the module isn't properly installed. Please remove it completely and follow the instructions here: https://foundryvtt.wiki/en/basics/Modules

You'll want to **install from manifest**. Paste the following URL into the box and you should be golden: https://github.com/casualchameleon/Bellows/releases/latest/download/module.json

Let me know if you need any more help. Good luck!

**Comment by DuckDungeon** [comment]
Cheers! That was the don't know what I don't know. Feeling a little sheepish, but I have more knowledge in my pocket.

Thanks so much! Fantastic module
