### ISSUE TITLE
Ambient Sounds

### ISSUE THREAD

**Issue by Sunamon** [casualchameleon/Bellows#5]
OMGOMGOMG! thank you for giving this module some love! I love what you've done with the place. I just noticed if I set up an ambient sound with a streamed file it doesn't seem to work. I'm on the latest stable 7.5. Thanks so much you've done a great job!

**Comment by casualchameleon** [comment]
I managed to hack a fix together for this, but I'll be rewriting the playlist and ambientsound code in the near-future. Please keep an eye out for bugs!
