### ISSUE TITLE
Weird Sidebar glitch

### ISSUE THREAD

**Issue by WookieeMatt** [casualchameleon/Bellows#57]
with V9 everything works but the sidebar jumps around when you hit play
![uMBo9IHYsi](https://user-images.githubusercontent.com/36809171/147714999-094cd183-7576-4a67-b675-215a1f3ff19f.gif)

**Comment by joshscorcher** [comment]
![image](https://user-images.githubusercontent.com/52643998/147842612-bc0e99fb-f4d4-4392-8100-c043a34806ce.png)
Here's the error message

**Comment by casualchameleon** [comment]
Fixed by @anoverga17. Tested and working in Bellows 0.4.4pre. Please open a new issue if you have any more problems. Thanks!
