### ISSUE TITLE
Changing the volume on a streamed track, after audio playback has begun, has no effect

### ISSUE THREAD

**Issue by bryancasler** [casualchameleon/Bellows#7]
Once you hit play on a streamed track, changing its volume on the track or on the Global "Playlist" ambiance slider has no effect on its volume. You have to stop the track, adjust the volume, and then play again for the volume change to take effect.

MacOS (Latest)
Chrome (Latest)
Foundry 0.7.5 (Latest)

**Comment by casualchameleon** [comment]
Can you please confirm you're using version 0.3.1 of Bellows?

**Comment by bryancasler** [comment]
I was able to upgrade, but when I hit play no sound comes out. I disabled and re-enabled the module, no change. Tried playing previously added tracks and adding fresh ones, still no dice and no errors in the console.

Recording: https://d.pr/v/q0Hzlx

**Comment by casualchameleon** [comment]
Thanks for the recording. So, one thing that is very suspicious is that 'no-player' in the console. This means that the youtube player hasn't managed to be created and that'll be why you have no sound. Could I please get a full mod list and I'll see if I can replicate based on that?
Cheers

**Comment by casualchameleon** [comment]
Hold off on this... another user has flagged up the same thing and I think I've found the cause. Thanks

**Comment by casualchameleon** [comment]
I think this has been fixed in the latest 0.3.2 release. Please try this out and let me know if it works for you.

**Comment by bryancasler** [comment]
Both the original issue and the new issue have been resolve. Thank You for jumping on this so quickly.
